// SPDX-License-Identifier: MIT
using System.Reflection;
using System.Runtime.InteropServices;

/// <summary>
/// Proves that the callbacks this binding hands to CNA have the shape CNA declares.
///
/// The prototype probe checks the *routes*, and for a callback parameter the managed side declares
/// as <c>nint</c> it can only check that a pointer is passed. What crosses at run time is a managed
/// function, and nothing compared its signature with the C typedef until this existed. Two real
/// defects were sitting behind that gap: an event callback took the sender as <c>nint</c> where CNA
/// passes a <c>CNA_Handle</c> (identical on a 64-bit target, four bytes short on a 32-bit one), and
/// the content-reader destroy callback returned a result code where CNA declares <c>void</c>.
///
/// Each check declares a C function with the signature derived from the *managed* member -- a
/// method carrying <c>UnmanagedCallersOnly</c>, or a function-pointer field of an interop struct --
/// and assigns it to the C typedef. Nothing here restates the header; the assignment is what fails.
/// </summary>
static class InteropCallbacks
{
    /// <summary>
    /// Which C typedef each managed callback implements.
    ///
    /// The pairing cannot be read from metadata -- a function pointer is handed to a route at a call
    /// site, not declared as implementing anything -- so it is listed, and each entry is a statement
    /// that the call site was read. It is deliberately small: two event shapes and the three
    /// content-reader callbacks account for every callback this binding provides.
    /// </summary>
    public static readonly (string Owner, string Member, string Typedef)[] Pairings =
    [
        ("CNA.NativeEventBridge", "OnNativeEvent", "CNA_GameEventCallback"),
        ("CNA.NativeEventBridge", "OnNativeEventWithSender", "CNA_GraphicsResourceDisposingCallback"),
        ("CnaContentTypeReaderCallbacks", "Create", "CNA_ContentTypeReaderCreateCallback"),
        ("CnaContentTypeReaderCallbacks", "Read", "CNA_ContentTypeReaderReadCallback"),
        ("CnaContentTypeReaderCallbacks", "Destroy", "CNA_ContentTypeReaderDestroyCallback"),
    ];

    /// <summary>The managed signature of one pairing, as C, or null when it cannot be found.</summary>
    private static (string Return, string[] Parameters)? Signature(string owner, string member)
    {
        foreach (Assembly assembly in new[] { typeof(CNA.Interop.CnaHandle).Assembly, typeof(CNA.Game).Assembly })
        {
            Type? type = assembly.GetTypes().FirstOrDefault(
                t => t.FullName == owner || t.Name == owner);
            if (type is null)
            {
                continue;
            }

            MethodInfo? method = type.GetMethod(
                member, BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.Public);
            if (method is not null)
            {
                string? returned = InteropPrototypes.CType(method.ReturnType);
                string?[] parameters = [.. method.GetParameters().Select(p => InteropPrototypes.CType(p.ParameterType))];
                return returned is null || parameters.Any(p => p is null)
                    ? null
                    : (returned, parameters.Select(p => p!).ToArray());
            }

            FieldInfo? field = type.GetField(
                member, BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public);
            if (field is not null && field.FieldType.IsFunctionPointer)
            {
                string? returned = InteropPrototypes.CType(field.FieldType.GetFunctionPointerReturnType());
                string?[] parameters =
                    [.. field.FieldType.GetFunctionPointerParameterTypes().Select(InteropPrototypes.CType)];
                return returned is null || parameters.Any(p => p is null)
                    ? null
                    : (returned, parameters.Select(p => p!).ToArray());
            }
        }

        return null;
    }

    public static string Generate(out List<string> unresolved)
    {
        unresolved = [];

        var text = new System.Text.StringBuilder();
        text.AppendLine("// SPDX-License-Identifier: MIT");
        text.AppendLine("// Generated by CNA.AbiVerify from the callbacks this binding provides. Do not edit.");
        text.AppendLine();
        text.AppendLine("#include <stddef.h>");
        text.AppendLine("#include <stdint.h>");
        text.AppendLine();
        text.AppendLine("#include \"CNA/C/cna.h\"");
        text.AppendLine();

        foreach ((string owner, string member, string typedef) in Pairings)
        {
            if (Signature(owner, member) is not { } signature)
            {
                unresolved.Add($"{owner}.{member}");
                continue;
            }

            // C11 requires a definition's parameters to be named, and -Wextra requires them to be
            // used, so each one is named and discarded. The body is irrelevant: what is under test
            // is the type the compiler gives this function, and whether it may be assigned to the
            // typedef CNA declares.
            string parameters = signature.Parameters.Length == 0
                ? "void"
                : string.Join(", ", signature.Parameters.Select((p, i) => $"{p} p{i}"));

            string function = $"mcb_{owner.Replace('.', '_')}_{member}";
            text.AppendLine($"// {owner}.{member}");
            text.AppendLine($"static {signature.Return} {function}({parameters})");
            text.AppendLine("{");
            for (int index = 0; index < signature.Parameters.Length; index++)
            {
                text.AppendLine($"    (void)p{index};");
            }

            if (signature.Return != "void")
            {
                text.AppendLine($"    return ({signature.Return})0;");
            }

            text.AppendLine("}");
            text.AppendLine($"{typedef} const chk_{function} = &{function};");
            text.AppendLine();
        }

        return text.ToString();
    }
}
